### ISSUE TITLE
Only constant format 8..16 bits supported.

### ISSUE THREAD

**Issue by Selur** [dubhater/vapoursynth-fluxsmooth#4]
Sorry, but I'm unsure that 'constant formats' are looking at the Vapoursynth color formats (http://www.vapoursynth.com/doc/pythonreference.html#format-constants).

Could you list the supported color formats which are supported?

**Comment by dubhater** [comment]
Generally speaking, clips are allowed to contain frames with different formats and different dimensions. Such clips will have VideoNode.format=None, and VideoNode.width=VideoNode.height=0. However, plenty of filters don't support this, most likely because of programmer laziness.

"Constant format" means that every frame in a clip has the same format, and that the format of the clip is known from the beginning, i.e. VideoNode.format is not None, but a valid Format object.

"Constant dimensions" means that every frame in a clip has the same dimensions, and that they are known from the beginning, i.e. VideoNode.width and VideoNode.height are both greater than 0.

readme.rst says "Only constant format 8..16 bits supported.", which is unfortunately incomplete. The clip must have constant format *and dimensions*, and it must have integer samples.
